language: c

sudo: false

install:
  - git clone https://github.com/radare/radare2
  - cd radare2
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s > /dev/null
  - make install > /dev/null
  - export R2_INCLUDE="-I/home/travis/build/Maijin/NES/radare2/libr/include"
  - cd ..

script:
  - make
  - make install
  - pwd

